name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@0b33ef444fd672ee683e20491b7798d937c69f8c
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
      with:
         ref: ${{ github.head_ref }}
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Update Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Apply action changes
